// --- Listado de emisoras ---

const ALL_STATIONS_DATA = {
    "España": [
        { "name": "Los 40 Principales", "url": "https://21223.live.streamtheworld.com/LOS40_SC" },
        { "name": "Los 40 Classic", "url": "http://21633.live.streamtheworld.com/LOS40_CLASSIC.mp3" },
        { "name": "Los 40 Dance", "url": "http://23543.live.streamtheworld.com/LOS40_DANCE.mp3" },
        { "name": "La Cope", "url": "https://net1-cope-rrcast.flumotion.com/cope/net2-low.mp3" },
        { "name": "Es Radio", "url": "http://livestreaming.esradio.fm/stream64.mp3" },
        { "name": "Kiss FM", "url": "http://kissfm.kissfmradio.cires21.com/kissfm.mp3" },
        { "name": "Cadena 100", "url": "https://cadena100-cope-rrcast.flumotion.com/cope/cadena100-low.mp3" },
        { "name": "Rock FM", "url": "https://rockfm-cope-rrcast.flumotion.com/cope/rockfm-low.mp3" },
        { "name": "La Ser", "url": "http://25603.live.streamtheworld.com/CADENASER.mp3" },
        { "name": "Hit FM", "url": "http://hitfm.kissfmradio.cires21.com/hitfm.mp3" },
        { "name": "Onda Cero", "url": "http://icecast-streaming.nice264.com/ondacero" },
        { "name": "Europa FM", "url": "https://str1.mediatelekom.net:9950/stream" },
        { "name": "Cadena Dial", "url": "https://27863.live.streamtheworld.com/CADENADIALAAC_SC" },
        { "name": "Radio Ole", "url": "http://21633.live.streamtheworld.com/RADIOLE.mp3" },
        { "name": "Gozadera FM", "url": "https://streaming.shoutcast.com/gozadera" },
        { "name": "Bikini FM", "url": "https://stream.emisorasmusicales.net/listen/bikini_fm/bikinifm.mp3" },
        { "name": "Radio Marca", "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/RADIOMARCA_NACIONAL.mp3?dist=onlineradiobox" },
        { "name": "Love 90", "url": "https://c6.auracast.net/radio/8090/radio.mp3" },
        { "name": "Radio Maria", "url": "https://dreamsiteradiocp2.com/proxy/rmspain2?mp=/stream" },
        { "name": "RAC 1", "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/RAC_1.mp3?dist=onlineradiobox" },
        { "name": "Radio Taxi", "url": "https://radiott-web.streaming-pro.com:6103/radiott.mp3" },
        { "name": "MetalFlames Radio", "url": "https://stream.zeno.fm/rb354pruvs8uv" },
        { "name": "1000 HITS SPAIN", "url": "https://c2.auracast.net/radio/8022/radio.mp3" },
        { "name": "Radio Planeta", "url": "https://radioplaneta.emitironline.com/radio" },
        { "name": "Ibiza Live Radio", "url": "https://streams.radio.co/sdc9cfaf77/listen" },
        { "name": "Zona Rap", "url": "https://radio.zonarap.es/listen/zona_rap_radio/radio.mp3" },
        { "name": "Loca Latino", "url": "https://srv7021.dns-lcinternet.com/8028/stream?hash=1733779053767.mp3" },
        { "name": "Radio Nature", "url": "https://stream.zeno.fm/sfpqezsh6f0uv" },
        { "name": "Carnaval FM", "url": "https://streaming2.elitecomunicacion.es:8108/stream" },
        { "name": "Mortal FM", "url": "http://stream2.beatproducciones.com:8044/;" },
        { "name": "IlloJuan Sounds", "url": "https://stream.zeno.fm/dfxrsplg0aiuv" },
        { "name": "Tormes FM", "url": "http://str1.mediatelekom.net:8738/;" }
    ],
    "Latinoamérica": [
        { "name": "Radio Que Onda", "url": "https://cast3.my-control-panel.com/proxy/gabriel4/stream" },
        { "name": "Universal Stereo", "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/XHFO_FM.mp3?dist=onlineradiobox" },
        { "name": "Radio Disney", "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/DISNEY_ARG_BA.mp3?dist=onlineradiobox" },
        { "name": "Radio Salsa", "url": "http://radio.domiplay.net:2002/;?type=http&nocache=7329;" }
    ],
	"Francia": [
		{ name: "Generations Rap Français", url: "https://generationfm-rap.ice.infomaniak.ch/generationfm-rap-high.mp3" },
		{ name: "NRJ", url: "https://streaming.nrjaudio.fm/oumvmk8fnozc?origine=radio.net" },
		{ name: "Skyrock", url: "https://icecast.skyrock.net/s/natio_aac_96k" },
		{ name: "RTL 2", url: "https://streamer-04.rtl.fr/rtl2-1-44-128" },
		{ name: "RTL 104.3 FM", url: "https://streamer-02.rtl.fr/rtl-1-44-128?aw_0_1st.broadcast_type=streaming&aw_0_1st.source_type=external&aw_0_1st.platform=external&aw_0_1st.media_category=fm&aw_0_1st.station=rtl&aw_0_1st.program=rtl&listen=wEbAwQMBgULAAQFAg8PBAEDBQ" },
		{ name: "France Info", url: "https://icecast.radiofrance.fr/franceinfo-midfi.mp3" },
		{ name: "NRJ REGGAETON", url: "https://streaming.nrjaudio.fm/ou8vs6gk7oiu?origine=radio.net&aw_0_1st.station=NRJ-Reggaeton" },
		{ name: "CHERIE FM", url: "https://streaming.nrjaudio.fm/ouuku85n3nje?origine=radio.net" },
		{ name: "Eurodance 90", url: "https://stream-eurodance90.fr/radio/8000/128.mp3" },
		{ name: "Générations - JUL", url: "https://generations-jul.ice.infomaniak.ch/generations-jul.mp3" },
		{ name: "Europe 2", url: "https://europe2.lmn.fm/europe2.mp3?aw_0_1st.playerid=lgrdnwsRadiofr" }		
    ],
    "Otros": [
        { "name": "Hits Radio Liberia", "url": "https://s4.radio.co/sada156669/listen" },
        { "name": "Radio Romanul", "url": "http://streaming.radioromanul.es:55556/web" },
        { "name": "J-Pop Powerplay", "url": "https://kathy.torontocast.com:3560/;" },
        { "name": "Splash Coffee", "url": "https://ais-sa2.cdnstream1.com/2345_128.mp3" },
        { "name": "Future Groove FM", "url": "https://streamer.radio.co/s4b3dafa6d/listen" },
        { "name": "One World Radio", "url": "https://playerservices.streamtheworld.com/api/livestream-redirect/OWR_INTERNATIONAL.mp3?dist=onlineradiobox" },
        { "name": "American Road Radio", "url": "https://c5.radioboss.fm:18224/stream" },
        { "name": "Planet Hip Hop", "url": "https://str3.openstream.co/1841" },
        { "name": "Radio Voz de Santo Tirso", "url": "https://servidor23.brlogic.com:7110/live" },
        { "name": "Truckers FM", "url": "https://radio.truckers.fm/" }
    ]
};

// --- TRADUCCIONES (Consolidado) ---
const translations = {
    "es": {
        "app_title": "📻 Radio Player",
        "player_title": "📻 Radio Player",
        "loading_data": "Cargando datos...",
        "inactive": "Inactivo",
        "button_play": "▶️ Iniciar",
        "button_pause": "⏸️ Pausar",
        "button_stop": "⏹️ Detener",
        "volume_label": "🔊",
        "search_placeholder": "Buscar emisora o país...",
        "settings_button": "Ajustes",
        "language_settings": "Configuración de Idioma",
        "select_language": "Seleccionar Idioma:",
        "status_playing": "▶️ Reproduciendo",
        "status_loading": "⏳ Cargando...",
        "status_paused": "⏸️ Pausado",
        "status_stopped": "Detenido",
        "status_error": "❌ ERROR: Stream Caído. Reporte usando la X.",
        "status_click_to_play": "Clic para iniciar",
        "current_none": "Ninguna",
		"current_station_prefix": "Emisora: ",
        "favorite_add": "Añadir a Favoritos",
        "favorite_remove": "Quitar de Favoritos",
        "group_favorites": "Favoritos ⭐",
        "disclaimer": "Proyecto de ningunomas. No somos responsables del contenido de los streams.",
        "changelog_link": "Registro de Cambios",
        "suggest_station_header": "Sugerir Nueva Emisora",
        "name_placeholder": "Nombre de la emisora",
        "url_placeholder": "URL del stream (ej: http://...)",
        "region_placeholder": "Región/País (ej: 'España 🇪🇸')",
        "mit_license": "Licencia MIT",
        "copy_suggest_button": "Copiar Sugerencia e ir a Steam",
        "report_modal_title": "🚨 Reportar Emisora Caída",
        "report_station_label": "Emisora:",
        "report_url_label": "URL:",
        "report_action_disclaimer": "La URL completa se enviará a Steam. Confirma para ir al hilo de reportes y pega la URL en un comentario.",
        "copy_success_status": "¡Mensaje de error copiado al portapapeles!",
        "copy_report_button": "Copiar Mensaje al Portapapeles",
        "go_to_steam_button": "Ir al hilo de Reportes en Steam",
		"group_España": "España 🇪🇸",
		"group_Latinoamérica": "Latinoamérica 🌎",
		"group_Francia": "Francia 🇫🇷",
		"group_Otros": "Otros 🌍",
		"group_favorites": "Favoritos ⭐",
		"copyright_text": "Ningunomas.",
		"license_intro": "Código fuente distribuido bajo la ",
		"license_name": "Licencia MIT",
		"project_title_button": "📜 Aclaración del Proyecto",
		"project_explanation": "Este reproductor ha sido creado para facilitar la adición de radio en vivo en Euro Truck Simulator 2 (ETS 2) y American Truck Simulator (ATS), especialmente para usuarios de NVIDIA GeForce NOW (GFN)",
		"project_warning": "⚠️ Aviso Importante: Las radios son streams públicos de terceros. Si hay algún problema de copyright o legal, la emisora será retirada inmediatamente.",
		"feedback_button_text": "Valoración / Comentarios",
        "copy_alert_error": "Error al copiar. Por favor, copia el texto manualmente: "
    },
    "en": {
        "app_title": "📻 Radio Player",
		"player_title": "📻 Radio Player",
		"loading_data": "Loading data...",
		"inactive": "Inactive",
		"button_play": "▶️ Play",
		"button_pause": "⏸️ Pause",
		"button_stop": "⏹️ Stop",
		"volume_label": "🔊",
		"search_placeholder": "Search station or country...",
		"settings_button": "Settings",
		"language_settings": "Language Settings",
		"select_language": "Select Language:",
		"status_playing": "▶️ Playing",
		"status_loading": "⏳ Loading...",
		"status_paused": "⏸️ Paused",
		"status_stopped": "Stopped",
		"status_error": "❌ ERROR: Stream Down. Report using the X.",
		"status_click_to_play": "Click to play",
		"current_none": "None",
		"current_station_prefix": "Station: ",
		"favorite_add": "Add to Favorites",
		"favorite_remove": "Remove from Favorites",
		"group_favorites": "Favorites ⭐",
		"disclaimer": "Project by ningunomas. We are not responsible for the content of the streams.",
		"changelog_link": "Changelog",
		"suggest_station_header": "Suggest New Station",
		"name_placeholder": "Station name",
		"url_placeholder": "Stream URL (e.g., http://...)",
		"region_placeholder": "Region/Country (e.g., 'Spain 🇪🇸')",
		"mit_license": "MIT License",
		"copy_suggest_button": "Copy Suggestion and go to Steam",
		"report_modal_title": "🚨 Report Down Station",
		"report_station_label": "Station:",
		"report_url_label": "URL:",
		"report_action_disclaimer": "The full URL will be sent to Steam. Confirm to go to the report thread and paste the URL in a comment.",
		"copy_success_status": "Error message copied to clipboard!",
		"copy_report_button": "Copy Message to Clipboard",
		"go_to_steam_button": "Go to Report Thread on Steam",
		"report_step_1_text": "Click to copy the full report to the clipboard. (The blue button)",
		"report_step_1_title": "1. Copy the text:",
		"report_station_prompt": "You are going to report the station: ",
		"copy_report_button": "Copy Message to Clipboard",
		"report_step_2_title": "2. Post on Steam:",
		"report_step_2_text": "Click to go to the report thread. **Once there, simply paste the text and post it.**",
		"group_España": "Spain 🇪🇸",
		"group_Latinoamérica": "Latin America 🌎",
		"group_Francia": "France 🇫🇷",
		"group_Otros": "Others 🌍",
		"group_favorites": "Favorites ⭐",
		"copyright_text": "Ningunomas.",
		"license_intro": "Source code distributed under the ",
		"license_name": "MIT License",
		"project_title_button": "📜 Project Clarification",
		"project_explanation": "This player was created to make it easier to add live radio to Euro Truck Simulator 2 (ETS 2) and American Truck Simulator (ATS), especially for NVIDIA GeForce NOW (GFN) users.",
		"project_warning": "⚠️ Important Notice: The radios are third-party public streams. If there are any copyright or legal issues, the station will be removed immediately.",
		"feedback_button_text": "Rating / Feedback",
		"copy_alert_error": "Error copying. Please copy the text manually: "
    },
    "de": {
        "app_title": "📻 Radio Player",
		"player_title": "📻 Radio Player",
		"loading_data": "Daten werden geladen...",
		"inactive": "Inaktiv",
		"button_play": "▶️ Starten",
		"button_pause": "⏸️ Pause",
		"button_stop": "⏹️ Stopp",
		"volume_label": "🔊",
		"search_placeholder": "Sender oder Land suchen...",
		"settings_button": "Einstellungen",
		"language_settings": "Spracheinstellungen",
		"select_language": "Sprache auswählen:",
		"status_playing": "▶️ Wird abgespielt",
		"status_loading": "⏳ Wird geladen...",
		"status_paused": "⏸️ Pausiert",
		"status_stopped": "Gestoppt",
		"status_error": "❌ FEHLER: Stream ausgefallen. Mit dem X melden.",
		"status_click_to_play": "Zum Starten klicken",
		"current_none": "Keine",
		"current_station_prefix": "Sender: ",
		"favorite_add": "Zu Favoriten hinzufügen",
		"favorite_remove": "Aus Favoriten entfernen",
		"group_favorites": "Favoriten ⭐",
		"disclaimer": "Projekt von ningunomas. Wir sind nicht für den Inhalt der Streams verantwortlich.",
		"changelog_link": "Änderungsprotokoll",
		"suggest_station_header": "Neuen Sender vorschlagen",
		"name_placeholder": "Name des Senders",
		"url_placeholder": "Stream-URL (z. B. http://...)",
		"region_placeholder": "Region/Land (z. B. 'Spanien 🇪🇸')",
		"mit_license": "MIT-Lizenz",
		"copy_suggest_button": "Vorschlag kopieren und zu Steam gehen",
		"report_modal_title": "🚨 Senderausfall melden",
		"report_station_label": "Sender:",
		"report_url_label": "URL:",
		"report_action_disclaimer": "Die vollständige URL wird an Steam gesendet. Bestätigen Sie, um zum Meldethread zu gehen und die URL in einem Kommentar einzufügen.",
		"copy_success_status": "Fehlermeldung in die Zwischenablage kopiert!",
		"copy_report_button": "Nachricht in Zwischenablage kopieren",
		"go_to_steam_button": "Zum Meldethread auf Steam gehen",
		"report_step_1_text": "Klicke, um den vollständigen Bericht in die Zwischenablage zu kopieren. (Die blaue Schaltfläche)",
		"report_step_1_title": "1. Text kopieren:",
		"report_station_prompt": "Du wirst den folgenden Sender melden: ",
		"copy_report_button": "Nachricht in Zwischenablage kopieren",
		"report_step_2_title": "2. Auf Steam posten:",
		"report_step_2_text": "Klicke, um zum Meldethread zu gehen. **Füge dort einfach den Text ein und veröffentliche ihn.**",
		"group_España": "Spanien 🇪🇸",
		"group_Latinoamérica": "Lateinamerika 🌎",
		"group_Francia": "Frankreich 🇫🇷",
		"group_Otros": "Andere 🌍",
		"group_favorites": "Favoriten ⭐",
		"copyright_text": "Ningunomas.",
		"license_intro": "Quellcode verteilt unter der ",
		"license_name": "MIT-Lizenz",
		"project_title_button": "📜 Projektklärung",
		"project_explanation": "Dieser Player wurde entwickelt, um das Hinzufügen von Live-Radio zu Euro Truck Simulator 2 (ETS 2) und American Truck Simulator (ATS) zu erleichtern, insbesondere für NVIDIA GeForce NOW (GFN)-Benutzer.",
		"project_warning": "⚠️ Wichtiger Hinweis: Die Radios sind öffentliche Streams von Drittanbietern. Wenn es Urheberrechts- oder rechtliche Probleme gibt, wird der Sender sofort entfernt.",
		"feedback_button_text": "Bewertung / Feedback",
		"copy_alert_error": "Fehler beim Kopieren. Bitte Text manuell kopieren: "

    },
	"fr": {
        "app_title": "📻 Lecteur Radio",
		"player_title": "📻 Lecteur Radio",
		"loading_data": "Chargement des données...",
		"inactive": "Inactif",
		"button_play": "▶️ Démarrer",
		"button_pause": "⏸️ Pause",
		"button_stop": "⏹️ Arrêter",
		"volume_label": "🔊",
		"search_placeholder": "Rechercher une station ou un pays...",
		"settings_button": "Paramètres",
		"language_settings": "Paramètres de langue",
		"select_language": "Choisir la langue :",
		"status_playing": "▶️ Lecture en cours",
		"status_loading": "⏳ Chargement...",
		"status_paused": "⏸️ En pause",
		"status_stopped": "Arrêté",
		"status_error": "❌ ERREUR : Flux interrompu. Signalez-le avec le X.",
		"status_click_to_play": "Cliquer pour démarrer",
		"current_none": "Aucun",
		"current_station_prefix": "Station : ",
		"favorite_add": "Ajouter aux favoris",
		"favorite_remove": "Retirer des favoris",
		"group_favorites": "Favoris ⭐",
		"disclaimer": "Projet par ningunomas. Nous ne sommes pas responsables du contenu des flux.",
		"changelog_link": "Journal des modifications",
		"suggest_station_header": "Suggérer une nouvelle station",
		"name_placeholder": "Nom de la station",
		"url_placeholder": "URL du flux (ex : http://...)",
		"region_placeholder": "Région/Pays (ex : 'Espagne 🇪🇸')",
		"mit_license": "Licence MIT",
		"copy_suggest_button": "Copier la suggestion et aller sur Steam",
		"report_modal_title": "🚨 Signaler une panne de station",
		"report_station_label": "Station :",
		"report_url_label": "URL :",
		"report_action_disclaimer": "L’URL complète sera envoyée à Steam. Confirmez pour accéder au fil de signalement et collez l’URL dans un commentaire.",
		"copy_success_status": "Message d’erreur copié dans le presse-papiers !",
		"copy_report_button": "Copier le message dans le presse-papiers",
		"go_to_steam_button": "Aller au fil de signalement sur Steam",
		"report_step_1_text": "Cliquez pour copier le rapport complet dans le presse-papiers. (Le bouton bleu)",
		"report_step_1_title": "1. Copier le texte :",
		"report_station_prompt": "Vous allez signaler la station suivante : ",
		"copy_report_button": "Copier le message dans le presse-papiers",
		"report_step_2_title": "2. Publier sur Steam :",
		"report_step_2_text": "Cliquez pour accéder au fil de signalement. **Collez simplement le texte et publiez-le.**",
		"group_España": "Espagne 🇪🇸",
		"group_Latinoamérica": "Amérique latine 🌎",
		"group_Francia": "France 🇫🇷",
		"group_Otros": "Autres 🌍",
		"group_favorites": "Favoris ⭐",
		"copyright_text": "Ningunomas.",
		"license_intro": "Code source distribué sous la ",
		"license_name": "Licence MIT",
		"project_title_button": "📜 Informations sur le projet",
		"project_explanation": "Ce lecteur a été conçu pour faciliter l’ajout de radios en direct à Euro Truck Simulator 2 (ETS 2) et American Truck Simulator (ATS), notamment pour les utilisateurs de NVIDIA GeForce NOW (GFN).",
		"project_warning": "⚠️ Avis important : Les radios sont des flux publics de tiers. En cas de problème de droits d’auteur ou légal, la station sera immédiatement retirée.",
		"feedback_button_text": "Évaluation / Commentaires",
		"copy_alert_error": "Erreur lors de la copie. Veuillez copier le texte manuellement : "
    }

};
